require("player")
require("mob")
require("jumper")
math.randomseed(os.time())
player = Player()
local test = Mob(200, 200)
local test2 = Jumper(500, 500)
love.update = function(dt)
  player:checkMovement()
  return player:updatePosition()
end
love.draw = function()
  player:draw()
  test:behavior()
  test:draw()
  test2:behavior()
  return test2:draw()
end
